<?php
declare(strict_types=1);
require_once __DIR__ . '/config.php';
function e(string $v): string { return htmlspecialchars($v, ENT_QUOTES, 'UTF-8'); }
function asset(string $p): string { return '/' . ltrim($p, '/'); }
function icon(string $n): string {
    $i = [
      'arrow'=>'<svg viewBox="0 0 24 24"><path d="M5 12h13M13 6l6 6-6 6"/></svg>',
      'chevron'=>'<svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg>',
      'github'=>'<svg viewBox="0 0 24 24"><path d="M12 .7a11.3 11.3 0 0 0-3.57 22c.57.1.78-.25.78-.55v-2.1c-3.17.69-3.84-1.35-3.84-1.35-.52-1.33-1.27-1.69-1.27-1.69-1.04-.71.08-.7.08-.7 1.15.08 1.76 1.18 1.76 1.18 1.02 1.75 2.67 1.24 3.32.95.1-.74.4-1.24.73-1.52-2.53-.29-5.19-1.27-5.19-5.65 0-1.25.45-2.27 1.18-3.07-.12-.29-.51-1.46.11-3.04 0 0 .96-.31 3.15 1.17a10.9 10.9 0 0 1 5.74 0c2.19-1.48 3.14-1.17 3.14-1.17.63 1.58.24 2.75.12 3.04.74.8 1.18 1.82 1.18 3.07 0 4.39-2.66 5.35-5.2 5.63.41.36.78 1.08.78 2.18v3.23c0 .31.21.66.79.55A11.3 11.3 0 0 0 12 .7Z"/></svg>',
      'linkedin'=>'<svg viewBox="0 0 24 24"><path d="M5.2 3.2a2.2 2.2 0 1 1 0 4.4 2.2 2.2 0 0 1 0-4.4ZM3.4 9h3.6v11.2H3.4V9Zm5.8 0h3.4v1.53h.05c.47-.88 1.63-1.81 3.35-1.81 3.58 0 4.24 2.36 4.24 5.43v6.05h-3.6v-5.36c0-1.28-.02-2.92-1.78-2.92-1.78 0-2.05 1.39-2.05 2.83v5.45H9.2V9Z"/></svg>',
      'mail'=>'<svg viewBox="0 0 24 24"><path d="M4 5h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Zm0 2 8 6 8-6"/></svg>',
      'menu'=>'<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',
      'close'=>'<svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>',
      'external'=>'<svg viewBox="0 0 24 24"><path d="M14 5h5v5M19 5l-9 9"/><path d="M19 13v5a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h5"/></svg>'
    ]; return $i[$n] ?? '';
}
function modules(): array { return [
'M201'=>['code'=>'M201','title'=>'Préparation d’un projet web','kicker'=>'Planifier avant de construire','description'=>'Transformer une idée en projet web clair : besoins, objectifs, périmètre, organisation et spécifications.','objectives'=>['Analyser un besoin','Rédiger des spécifications','Définir un périmètre réaliste','Organiser les étapes du projet'],'skills'=>['Cadrage','Cahier des charges','Analyse des besoins','Planification'],'accent'=>'blue'],
'M202'=>['code'=>'M202','title'=>'Approche agile','kicker'=>'Construire en itérations','description'=>'Découvrir Scrum et les pratiques qui permettent à une équipe de livrer, tester et améliorer progressivement.','objectives'=>['Comprendre Scrum','Écrire des User Stories','Prioriser un Product Backlog','Préparer un Sprint'],'skills'=>['Scrum','Sprint','Backlog','User Stories'],'accent'=>'violet'],
'M203'=>['code'=>'M203','title'=>'Gestion des données','kicker'=>'Structurer l’information','description'=>'Concevoir des bases de données cohérentes et manipuler les données avec SQL et des opérations CRUD.','objectives'=>['Modéliser les données','Créer des tables','Écrire des requêtes SQL','Gérer un CRUD'],'skills'=>['MySQL','SQL','Relations','CRUD'],'accent'=>'cyan'],
'M204'=>['code'=>'M204','title'=>'Développement front-end','kicker'=>'Donner vie à l’interface','description'=>'Construire des interfaces accessibles, responsives et interactives avec HTML, CSS et JavaScript.','objectives'=>['Structurer une page','Créer un responsive design','Ajouter de l’interactivité','Appliquer les bases UI/UX'],'skills'=>['HTML','CSS','JavaScript','Bootstrap','jQuery','UI/UX'],'accent'=>'green'],
'M205'=>['code'=>'M205','title'=>'Développement back-end','kicker'=>'Construire la logique serveur','description'=>'Développer la logique métier, connecter une base de données et exposer des fonctionnalités côté serveur.','objectives'=>['Programmer en PHP','Structurer avec la POO','Créer des APIs','Gérer une authentification'],'skills'=>['PHP','POO / OOP','APIs','MySQL','Authentication'],'accent'=>'orange'],
'M206'=>['code'=>'M206','title'=>'Création d’une application Cloud native','kicker'=>'Penser déploiement et scalabilité','description'=>'Découvrir les fondamentaux cloud-native : APIs, conteneurs, déploiement, disponibilité et pratiques DevOps.','objectives'=>['Comprendre le cloud','Découvrir les conteneurs','Préparer un déploiement','Comprendre la scalabilité'],'skills'=>['Cloud','Containers','APIs','Deployment','DevOps'],'accent'=>'pink']
]; }
function getModule(string $code): array { $d=modules(); return $d[$code] ?? []; }
function projectData(): array { return [
['title'=>'Mawjoud Market','module'=>'M201','description'=>'Prototype de marketplace pour organiser la découverte de produits, catégories et besoins utilisateurs.','problem'=>'Rendre une offre locale plus simple à consulter et à organiser.','solution'=>'Une expérience de catalogue structurée avec navigation claire et fiches produits.','features'=>['Catalogue','Catégories','Fiches produits','Parcours responsive'],'technologies'=>['HTML','CSS','JavaScript'],'image'=>'/images/projects/mawjoud-market.svg','github'=>'#','demo'=>'#','documentation'=>'/documents/M201/project-mawjoud-market.pdf'],
['title'=>'SprintBoard','module'=>'M202','description'=>'Tableau de suivi pédagogique inspiré de Scrum pour visualiser backlog, sprint et tâches terminées.','problem'=>'Avoir une vision rapide de ce qui est à faire, en cours et livré.','solution'=>'Un board simple avec états de tâches et priorités visibles.','features'=>['Backlog','Sprint','Statuts','Priorités'],'technologies'=>['HTML','CSS','JavaScript'],'image'=>'/images/projects/sprintboard.svg','github'=>'#','demo'=>'#','documentation'=>'/documents/M202/project-sprintboard.pdf'],
['title'=>'StockFlow','module'=>'M203','description'=>'Mini système de gestion de stock pour pratiquer la modélisation, le CRUD et les requêtes SQL.','problem'=>'Éviter les informations dispersées sur les articles et leurs mouvements.','solution'=>'Un modèle de données relationnel accompagné d’opérations CRUD.','features'=>['Produits','Stock','CRUD','Relations SQL'],'technologies'=>['PHP','MySQL','SQL'],'image'=>'/images/projects/stockflow.svg','github'=>'#','demo'=>'#','documentation'=>'/documents/M203/project-stockflow.pdf'],
['title'=>'CasaGuide UI','module'=>'M204','description'=>'Prototype d’interface responsive mettant l’accent sur la hiérarchie visuelle et les micro-interactions.','problem'=>'Présenter beaucoup d’informations locales sans surcharger l’écran.','solution'=>'Une grille responsive, des cartes et des états interactifs légers.','features'=>['Responsive grid','Cards','Interactions','UI states'],'technologies'=>['HTML','CSS','JavaScript','jQuery'],'image'=>'/images/projects/casaguide.svg','github'=>'#','demo'=>'#','documentation'=>'/documents/M204/project-casaguide.pdf'],
['title'=>'Campus API','module'=>'M205','description'=>'API PHP pédagogique pour gérer des ressources étudiantes et pratiquer validation, CRUD et JSON.','problem'=>'Permettre à plusieurs interfaces de consommer les mêmes données.','solution'=>'Endpoints structurés avec validation des entrées et réponses JSON cohérentes.','features'=>['REST-like endpoints','Validation','JSON','CRUD'],'technologies'=>['PHP','MySQL','JSON','APIs'],'image'=>'/images/projects/campus-api.svg','github'=>'#','demo'=>'#','documentation'=>'/documents/M205/project-campus-api.pdf'],
['title'=>'CloudBox Deploy','module'=>'M206','description'=>'Prototype de flux de déploiement qui visualise les étapes d’une application jusqu’à sa mise en production.','problem'=>'Comprendre visuellement la chaîne build → deploy → monitor.','solution'=>'Une vue pédagogique des étapes cloud-native et DevOps.','features'=>['Build','Container','Deploy','Monitor'],'technologies'=>['Cloud','Containers','APIs','DevOps'],'image'=>'/images/projects/cloudbox.svg','github'=>'#','demo'=>'#','documentation'=>'/documents/M206/project-cloudbox.pdf']
]; }
function ateliersData(): array { $r=[]; foreach(modules() as $code=>$m){ $r[$code]=[
['number'=>'01','title'=>'Atelier 01 — Mise en pratique','description'=>'Exercice pédagogique pour transformer les concepts du module en livrable concret.','objective'=>$m['objectives'][0],'technologies'=>$m['skills'],'result'=>'Livrable de démonstration à enrichir avec le travail réel.','image'=>"/images/modules/$code/atelier-01.svg",'document'=>"/documents/$code/atelier-01.pdf"],
['number'=>'02','title'=>'Atelier 02 — Mini projet','description'=>'Deuxième exercice pour consolider la méthode et relier plusieurs notions dans un même scénario.','objective'=>$m['objectives'][1],'technologies'=>$m['skills'],'result'=>'Prototype fonctionnel à remplacer par le vrai atelier réalisé.','image'=>"/images/modules/$code/atelier-02.svg",'document'=>"/documents/$code/atelier-02.pdf"]]; } return $r; }
function startPage(string $title,string $description,string $active='',string $eyebrow=''):void { ?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?=e($title)?></title><meta name="description" content="<?=e($description)?>"><meta name="theme-color" content="#050505"><meta property="og:title" content="<?=e($title)?>"><meta property="og:description" content="<?=e($description)?>"><meta property="og:type" content="website"><link rel="icon" href="<?=asset('images/profile/favicon.svg')?>" type="image/svg+xml"><link rel="stylesheet" href="<?=asset('api/style.css')?>"><script>window.PORTFOLIO_CSRF=<?=json_encode($_SESSION['csrf_token']??'')?>;</script><script defer src="https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.min.js"></script><script defer src="<?=asset('api/script.js')?>"></script></head><body>
<div class="noise" aria-hidden="true"></div><div class="ambient ambient-a" aria-hidden="true"></div><div class="ambient ambient-b" aria-hidden="true"></div>
<header class="site-header"><nav class="nav-shell" aria-label="Navigation principale"><a class="brand" href="/#top" aria-label="Accueil"><span class="brand-mark">HC</span><span class="brand-copy"><strong>Houssam</strong><small>Full Stack</small></span></a><div class="nav-links"><a class="nav-link <?= $active==='home'?'is-active':'' ?>" href="/#top">Home</a><a class="nav-link <?= $active==='about'?'is-active':'' ?>" href="/#about">About</a><a class="nav-link" href="/#modules">Modules</a><a class="nav-link <?= $active==='projects'?'is-active':'' ?>" href="/#projects">Projects</a><a class="nav-link <?= $active==='contact'?'is-active':'' ?>" href="/#contact">Contact</a></div><div class="nav-actions"><a class="nav-pill" href="/M204.php">Explore M204 <?=icon('arrow')?></a><button class="icon-button menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-nav"><?=icon('menu')?></button></div></nav><div class="mobile-nav" id="mobile-nav" aria-hidden="true"><div class="mobile-nav-inner"><button class="icon-button menu-close" type="button" aria-label="Fermer"><?=icon('close')?></button><a href="/#top" class="mobile-link">Home</a><a href="/#about" class="mobile-link">About</a><a href="/#modules" class="mobile-link">Modules</a><a href="/#projects" class="mobile-link">Projects</a><a href="/#contact" class="mobile-link">Contact</a><div class="mobile-modules"><?php foreach(modules() as $code=>$m): ?><a href="/<?=$code?>.php"><?=$code?></a><?php endforeach; ?></div></div></div></header><main>
<?php if($eyebrow!==''): ?><section class="page-heading section-pad"><div class="container narrow"><span class="eyebrow"><?=e($eyebrow)?></span><h1><?=e($title)?></h1><p class="lead"><?=e($description)?></p></div></section><?php endif; ?><?php }
function endPage():void { ?></main><footer class="site-footer"><div class="container footer-grid"><div><span class="eyebrow">PORTFOLIO</span><h2>Build. Learn. Ship.</h2><p>Une trace claire du parcours OFPPT et des projets Web Full Stack.</p></div><div class="footer-links"><a href="/#top">Home</a><a href="/#modules">Modules</a><a href="/#projects">Projects</a><a href="/#contact">Contact</a></div><div class="footer-meta"><span>© <?=date('Y')?> Houssam Chelha</span><span>Morocco · OFPPT</span></div></div></footer><div class="toast" id="toast" role="status" aria-live="polite"></div></body></html><?php }
function renderModuleCard(array $m):string { ob_start(); ?><a class="module-card glass-card reveal" href="/<?=e($m['code'])?>.php"><div class="card-top"><span class="module-code"><?=e($m['code'])?></span><span class="mini-icon"><?=icon('chevron')?></span></div><span class="card-kicker"><?=e($m['kicker'])?></span><h3><?=e($m['title'])?></h3><p><?=e($m['description'])?></p><div class="tag-row"><?php foreach(array_slice($m['skills'],0,4) as $s): ?><span class="tag"><?=e($s)?></span><?php endforeach; ?></div><span class="card-link">Voir le module <?=icon('arrow')?></span></a><?php return trim(ob_get_clean()); }
function renderProjectCard(array $p):string { ob_start(); ?><article class="project-card glass-card reveal"><div class="project-visual"><img src="<?=e($p['image'])?>" alt="Illustration du projet <?=e($p['title'])?>" loading="lazy"><span class="project-module"><?=e($p['module'])?></span></div><div class="project-body"><div class="project-title-row"><div><span class="card-kicker">Prototype pédagogique</span><h3><?=e($p['title'])?></h3></div><?=icon('arrow')?></div><p><?=e($p['description'])?></p><div class="tag-row"><?php foreach($p['technologies'] as $t): ?><span class="tag"><?=e($t)?></span><?php endforeach; ?></div><div class="project-actions"><a class="text-link" href="<?=e($p['documentation'])?>" target="_blank" rel="noreferrer">Documentation <?=icon('external')?></a><a class="text-link" href="<?=e($p['github'])?>">GitHub <?=icon('github')?></a></div></div></article><?php return trim(ob_get_clean()); }
function renderAtelierCard(array $a):string { ob_start(); ?><article class="atelier-card glass-card reveal"><div class="atelier-number"><?=e($a['number'])?></div><div class="atelier-content"><div class="project-visual compact"><img src="<?=e($a['image'])?>" alt="Illustration de <?=e($a['title'])?>" loading="lazy"></div><div class="atelier-copy"><span class="card-kicker">Atelier OFPPT</span><h3><?=e($a['title'])?></h3><p><?=e($a['description'])?></p><p><strong>Objectif :</strong> <?=e($a['objective'])?></p><div class="tag-row"><?php foreach(array_slice($a['technologies'],0,5) as $t): ?><span class="tag"><?=e($t)?></span><?php endforeach; ?></div><div class="result-note"><span>Résultat</span><?=e($a['result'])?></div><a class="text-link" href="<?=e($a['document'])?>" target="_blank" rel="noreferrer">Ouvrir le document <?=icon('external')?></a></div></div></article><?php return trim(ob_get_clean()); }
